CREATE SCHEMA IF NOT EXISTS work;

CREATE TABLE IF NOT EXISTS work.garage(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    address TEXT,
    phone_number VARCHAR(20),
    email VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS work.opening_time (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week varchar(20) not null,
    start_time time not null,
    end_time time not null,
    garage_id int,
    FOREIGN KEY (garage_id) REFERENCES work.garage(id),
    UNIQUE (day_of_week, garage_id)
);

CREATE TABLE IF NOT EXISTS work.vehicle(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand VARCHAR(50) NOT NULL,
    fuel_type VARCHAR(100),
    fabrication_year INT,
    garage_id INT,
    FOREIGN KEY (garage_id) REFERENCES work.garage(id)
);

CREATE TABLE IF NOT EXISTS work.accessory(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL,
    vehicle_id INT,
    FOREIGN KEY (vehicle_id) REFERENCES work.vehicle(id)
);

